# Generated by Django 4.2.4 on 2023-10-06 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('mail', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='imagen')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='GrupoInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'GrupoInforme',
                'verbose_name_plural': 'Grupos',
                'db_table': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado Fecha')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado Fecha')),
                ('grupos', models.ManyToManyField(to='Informes.grupoinforme')),
            ],
            options={
                'verbose_name': 'Informe',
                'db_table': 'informe',
            },
        ),
        migrations.CreateModel(
            name='MenuInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'MenuInforme',
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='InformeEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True, max_length=400, null=True, verbose_name='Iframe')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Informes.empresa')),
                ('informe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Informes.informe')),
            ],
            options={
                'verbose_name': 'Informe PowerBI',
                'verbose_name_plural': 'Informes PowerBI',
                'db_table': 'InformeUrl',
            },
        ),
        migrations.AddField(
            model_name='informe',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Informes.menuinforme'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='grupos',
            field=models.ManyToManyField(to='Informes.grupoinforme'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='informes',
            field=models.ManyToManyField(through='Informes.InformeEmpresa', to='Informes.informe'),
        ),
    ]
