# Generated by Django 4.2.4 on 2023-10-10 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Login Fecha/Hora')),
                ('ip_address', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Acceso de Usuario',
                'verbose_name_plural': 'Accesos de Usuarios',
                'db_table': 'acceso',
                'ordering': ['id'],
                'permissions': (('view_AccessUser', 'Can view Acceso de Usuario'), ('delete_AccessUser', 'Can delete Acceso de Usuario')),
                'default_permissions': (),
            },
        ),
    ]
