# Generated by Django 4.2.4 on 2023-10-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Autenticacion', '0002_accessuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accessuser',
            table='accessuser',
        ),
    ]
